# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PERL=5.22.2.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ioPixxWiDuMiF+CUzKezdP/DEsltwYreT38HK889PzvjjdFgAPunezVMmukxYnGwcf7dZivaoh3APCQt3h46FIilXfRPAmlWEamYo6lUaoLBMYae3kgueJ41u923c6kgx1Y1rb8a8m4/mM9Zguy4VhFR5hlZTLyTR4DJ3CqVADRothuo3Jn7DW5PPRgfWS5FZ+pPH8RBdc0Yao8nEv/7U6W82F+ycndWAPjvc8ZhvjWUpCoa/0FWtzB8aa57023yrvxmi1yn2nny/f++nBaW+boKwuYyWNCqWuHsnPGZSBg8n3Pn2iRfLYMyQ/xRLb1idBeYR7rhoUYzyEa9kPl1+H8V1/dsp9TmALmL0F9t9QMewY5Ge73lJMzKbRz46YIQmKDiYqNkJ1jVH1/IvG3LK9+KEv522v8AK6XgSKroI8gX+0i7rtnKZNdOW6AYNDOR3uN8JIgsr7+ll9gy7fJZng/j4ENC5v5/8llgJ6W6t0iLTjfXo7G2R6d2yj0ymKFCPFlu25Y/xiVJLrgEhQUKwsI7oL6iZ2azqlRNQTmjj/rzYCQDVlXLDkkKbn1zWz2svIUSVTH3Q3Dz/AUWTs6891+dPi6VBNltFFb8wWDT+4OK6PW0YXDjsJ1/phJOzvpm256RbFcXECLqWA9GOqAZrGBHuCBHtPR9WoJkCI8W4/E="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
