travis:
  secure:
    BINSTAR_TOKEN: ioPixxWiDuMiF+CUzKezdP/DEsltwYreT38HK889PzvjjdFgAPunezVMmukxYnGwcf7dZivaoh3APCQt3h46FIilXfRPAmlWEamYo6lUaoLBMYae3kgueJ41u923c6kgx1Y1rb8a8m4/mM9Zguy4VhFR5hlZTLyTR4DJ3CqVADRothuo3Jn7DW5PPRgfWS5FZ+pPH8RBdc0Yao8nEv/7U6W82F+ycndWAPjvc8ZhvjWUpCoa/0FWtzB8aa57023yrvxmi1yn2nny/f++nBaW+boKwuYyWNCqWuHsnPGZSBg8n3Pn2iRfLYMyQ/xRLb1idBeYR7rhoUYzyEa9kPl1+H8V1/dsp9TmALmL0F9t9QMewY5Ge73lJMzKbRz46YIQmKDiYqNkJ1jVH1/IvG3LK9+KEv522v8AK6XgSKroI8gX+0i7rtnKZNdOW6AYNDOR3uN8JIgsr7+ll9gy7fJZng/j4ENC5v5/8llgJ6W6t0iLTjfXo7G2R6d2yj0ymKFCPFlu25Y/xiVJLrgEhQUKwsI7oL6iZ2azqlRNQTmjj/rzYCQDVlXLDkkKbn1zWz2svIUSVTH3Q3Dz/AUWTs6891+dPi6VBNltFFb8wWDT+4OK6PW0YXDjsJ1/phJOzvpm256RbFcXECLqWA9GOqAZrGBHuCBHtPR9WoJkCI8W4/E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
