travis:
  secure:
    BINSTAR_TOKEN: kgcUTPYYgQ/qK61couwsAJUuUTBqDgjIW6eETaAAC2ysSi4Z+3myP5sNKDd6xLxf7ZNs1WHKYRyxJsG79F3KS6nUNC8idr4c7IxT2xZ84YJqD0RAZmNFsCrd7VxcL7wU44OyqaF6GJqxxscX9DlWN0PNljX1wx8M3OcEQdBNgqxjlcJxlPyXiyO1tUm2B1p2Kp8em5Yr8RIA4qtT1liW1rf0yj4uDV3Qe0TpPlms+nF0m/TjTHe9PVPZsOlLYsNQhQWkeRnYSYCqaIPip39mD8rIWSfHC9Ei9iJ8b36onC5Xz8vFJ44WiqpzAYAyJRvgnNF6Dv47RwFFcPtjqVicdiK101We7ClzxA+LLYOPe6exdONpkntVUWsSGac//aMERepPbiZ4+09wz6UMLoMXRwUozDlE5n6lrABH6BZGglofZ2Y+LE3DsaPJYEm1IiYaMGp4/Y6H8JKOG1bTQjV1wWN+v8641gHGMzHMOrq/qXLsQ7+P4u7cfYFkvqcVdOP7nETPA+Fm+dvVwjb49pf6a3qf+1nX/qnSxmXo8/qd3XKcr8cEqfZ53HfnrXu3PoJ7u+EoRPbMeEZ6wXmb0w0T2+h9NTrNafEdZqX7d3a/mh6Mfveuufdylklw7+5Kiez4aPewsLrudHXk17lkAdHCFDzLAd4qBvmAlG6E1rLakdM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
