travis:
  secure:
    BINSTAR_TOKEN: hQ5qEIy4lgxNckmjdTILWQcQSoTxOucig7bEdgzhGtmt4dqqi9TyKd59AJXeKsFUA0E2Mpivrl1mLFlkkdo9vA04PU2tF7IdlxLG/ca2BUn2HvKtC+DBCDJSqDSZZTojIR7BQxDu4bCTeprMAeJjmTa1j3joK/EdSxdR9HfdCs4z8qP2Eb+BPLmT0MfX5oDAWUop8FYGf6+ubjB30OBumputI+WrB88DMigvB7gjbe9PivUi4uya3TOQvNI7G/972uX+lRrlys69iwrVR015in5GnqKO1ncnOuc745478Z3rP4Ql8SC5Se7FFjuhhDaNv+mEvOXClRdSD2tFL1yNwRl9pvzgpZN8eqgm49JcQX389r12LUohjQf6BUzpsaGBx+TlaEHQRb3P1Z0rQly+eStyp6Q53WsAH9C3HL12BSenhNqQzbD8lf3KhZO4Kd7njfxIYWiNg5NouFBYOXZcB6MsXO4ZHYgGEAsUYGCfXHd/D4nCMgnVimWFoMxJNB6ltggYvMk6wPB7m/IAdmUgbYPy34xeFMjvnmchp/zGyEDrCOaWgL7SGGaROWv226LWXcPwZPI7HArXhq+LGnHzta/gc3/8jTeWjQLC1bR9wB7vsUsnZLmd1g7pi3FdvDtkgKE8GMk4GLpJpiCGqwe4+DQJQ1NoOhOPy/k3MOyIXig=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
